// Project
export const REQUEST_PROJECT = 'REQUEST_PROJECT';
export const RECEIVE_PROJECT = 'RECEIVE_PROJECT';
export const FETCH_PROJECT = 'FETCH_PROJECT';
export const FETCH_PROJECT_PENDING = 'FETCH_PROJECT_PENDING';
export const FETCH_PROJECT_FULFILLED = 'FETCH_PROJECT_FULFILLED';
export const FETCH_PROJECT_REJECTED = 'FETCH_PROJECT_REJECTED';

// Form
export const ADD_FORM_REF = 'ADD_FORM_REF';
export const SET_UP_FORM_ADD = 'SET_UP_FORM_ADD';
export const SET_UP_FORM_EDIT = 'SET_UP_FORM_EDIT';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const PREVIOUS_QUESTION = 'PREVIOUS_QUESTION';
export const ADD_ANSWER_TO_ENTRY = 'ADD_ANSWER_TO_ENTRY';
export const ADD_TITLE_TO_ENTRY = 'ADD_TITLE_TO_ENTRY';
export const SET_WAS_JUMPED = 'SET_WAS_JUMPED';
export const ENTRY_COMPLETE = 'ENTRY_COMPLETE';
export const ENTRY_INCOMPLETE = 'ENTRY_INCOMPLETE';
export const RESET_FORM = 'RESET_FORM';

// Branch
export const SET_UP_BRANCH_ADD = 'SET_UP_BRANCH_ADD';
export const SET_UP_BRANCH_EDIT = 'SET_UP_BRANCH_EDIT';
export const NEXT_QUESTION_BRANCH = 'NEXT_QUESTION_BRANCH';
export const PREVIOUS_QUESTION_BRANCH = 'PREVIOUS_QUESTION_BRANCH';
export const ADD_ANSWER_TO_ENTRY_BRANCH = 'ADD_ANSWER_TO_ENTRY_BRANCH';
export const ADD_TITLE_TO_ENTRY_BRANCH = 'ADD_TITLE_TO_ENTRY_BRANCH';
export const SET_WAS_JUMPED_BRANCH = 'SET_WAS_JUMPED_BRANCH';
export const RESET_BRANCH = 'RESET_BRANCH';
export const SAVE_BRANCH = 'SAVE_BRANCH';
export const SAVE_ENTRY_BRANCH = 'SAVE_ENTRY_BRANCH';

// Answer
export const SET_ANSWER = 'SET_ANSWER';
export const SET_ANSWERS = 'SET_ANSWERS';
export const SET_CONFIRM_ANSWER = 'SET_CONFIRM_ANSWER';
export const RESET_BRANCH_ANSWERS = 'RESET_BRANCH_ANSWERS';
export const RESET_CONFIRM_ANSWERS = 'RESET_CONFIRM_ANSWERS';
export const RESET_ALL_ANSWERS = 'RESET_All_ANSWERS';

// Upload
export const UPLOADING = 'UPLOADING';
export const FINISHED_UPLOADING = 'FINISHED_UPLOADING';
export const FINISHED_UPLOADING_WITH_ERRORS = 'FINISHED_UPLOADING_WITH_ERRORS';
export const CLEAR_ALL_UPLOAD_ERRORS = 'CLEAR_ALL_UPLOAD_ERRORS';

// Validator
export const REQUEST_VALIDATION = 'REQUEST_VALIDATION';
export const FINISHED_VALIDATION = 'FINISHED_VALIDATION';
export const ADD_ERRORS = 'ADD_ERRORS';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_ALL_ERRORS = 'CLEAR_ALL_ERRORS';

// General app actions
export const EXTERNAL = 'EXTERNAL';
export const INTERNAL = 'INTERNAL';
export const BRANCH_OPEN = 'BRANCH_OPEN';
export const BRANCH_CLOSED = 'BRANCH_CLOSED';
export const RESET_APP = 'RESET_APP';
export const RESET_APP_COMPLETE = 'RESET_APP_COMPLETE';
export const FETCH_STATUS_CODES = 'FETCH_STATUS_CODES';
export const FETCH_STATUS_CODES_PENDING = 'FETCH_STATUS_CODES_PENDING';
export const FETCH_STATUS_CODES_FULFILLED = 'FETCH_STATUS_CODES_FULFILLED';
export const FETCH_STATUS_CODES_REJECTED = 'FETCH_STATUS_CODES_REJECTED';

// Entry
export const FETCH_ENTRY = 'FETCH_ENTRY';
export const FETCH_ENTRY_PENDING = 'FETCH_ENTRY_PENDING';
export const FETCH_ENTRY_FULFILLED = 'FETCH_ENTRY_FULFILLED';
export const FETCH_ENTRY_REJECTED = 'FETCH_ENTRY_REJECTED';
export const SET_UP_ENTRY_ADD = 'SET_UP_ENTRY_ADD';

// Branch Entry
export const FETCH_ENTRY_BRANCH_PENDING = 'FETCH_ENTRY_BRANCH_PENDING';
export const FETCH_ENTRY_BRANCH_FULFILLED = 'FETCH_ENTRY_BRANCH_FULFILLED';
export const FETCH_ENTRY_BRANCH_REJECTED = 'FETCH_ENTRY_BRANCH_REJECTED';
export const SET_UP_ENTRY_BRANCH_ADD = 'SET_UP_ENTRY_BRANCH_ADD';
export const SET_UP_ENTRY_BRANCH_EDIT = 'SET_UP_ENTRY_BRANCH_EDIT';
export const ENTRY_COMPLETE_BRANCH = 'ENTRY_COMPLETE_BRANCH';
export const ENTRY_INCOMPLETE_BRANCH = 'ENTRY_INCOMPLETE_BRANCH';
export const DELETE_BRANCH = 'DELETE_BRANCH';

// Toast
export const SHOW_TOAST_SUCCESS = 'SHOW_TOAST_SUCCESS';
export const HIDE_TOAST_SUCCESS = 'HIDE_TOAST_SUCCESS';
export const SHOW_TOAST_ERROR = 'SHOW_TOAST_ERROR';
export const HIDE_TOAST_ERROR = 'HIDE_TOAST_ERROR';
