const strings = {
    save: 'Save',
    save_entry: 'Save Entry',
    save_and_quit: 'Save and Quit',
    quit: 'Exit',
    exit: 'Exit',
    want_to_quit: 'Are you sure you want to Exit?',
    upload_error: 'There is a problem with one of your answers. Please go back and make any necessary corrections.',
    entry_completed: 'Entry Completed',
    go_back: 'Go Back',
    dismiss: 'Dismiss',
    add_another_entry: 'Add Another Entry',
    edit: 'Edit',
    delete: 'Delete',
    delete_branch_title: 'Delete Branch Entry',
    delete_branch: 'Are you sure you want to delete this branch entry?',
    save_branch_entry: 'Save Branch Entry',
    viewing_branches: 'Please note: To view existing branch entries you can use the Epicollect5 Data Viewer.',
    add_branch: 'Add Branch',
    successfully_uploaded: 'Successfully Uploaded.',
    thank_you_for_your_submission: 'Thank you for your submission. You can now close this tab/window.',
    are_you_sure_save_and_quit: 'Are you sure you want to Save and Quit?',
    date_selected_is: 'The date selected is:',
    time_selected_is: 'The time selected is:',
    type_answer_here: 'Type answer here...',
    no_location_found: 'No location found, please retry.',
    location_updated: 'Location updated.',
    invalid_coords: 'Invalid coordinates.',
    location_not_available: 'Location is not available.',
    search: 'Search',
    address: 'Address',
    ie_london: 'i.e. London',
    update_location: 'Update Location',
    latitude: 'Latitude',
    longitude: 'Longitude',
    how_do_i_get_location: 'How do I get a location?',
    help: 'Help'
};

export default strings;
